import streamlit as st
from google.cloud import aiplatform
import vertexai.preview.vision_models
import tempfile
import os
import mimetypes
from typing import Iterator
import time

PROJECT_ID = 'mg-ce-demos' # change to your GCP project ID
REGION = 'us-central1' # change to the appropriate region

# Initialize Vertex AI
vertexai.init(project = PROJECT_ID, location = REGION)

# Add clear history button in the sidebar
with st.sidebar:
    st.header("Generate Images with Imagen")
#    st.write(f"You are logged in as {st.session_state.role}.")
    model_name = st.selectbox(
        "Select Imagen Model",
        ["imagen-3.0-generate-001"],
        index=0
    )
    num_images = st.slider("How many images to generate?", 1, 4)

MODEL = vertexai.preview.vision_models.ImageGenerationModel.from_pretrained(model_name)

image_list = []

with st.form("Image Generator"):
    image_prompt = st.text_area("Prompt for image generation")
    submitted = st.form_submit_button("Generate Image(s)")
    if submitted and len(image_prompt)>0:
        images = MODEL.generate_images(
            prompt=image_prompt,
            number_of_images=num_images,
            aspect_ratio="1:1",
        )
        
        for img in images:
            image_list.append(img._image_bytes)
            
st.image(image_list, caption=["Generated by Imagen 3"]*len(image_list))